### PR TITLE
Feature/svg widget

### PR DESCRIPTION
**Pull request by jrwarwick**
SVG linked and inline as an optional special Element for complex geometric Elements, such as the classic circular XY directional control. I know this digresses some from this being a "CSS framework", so if you don't want it in here, no hard feelings.

### CODE REVIEW

**Comment by joernweissenborn** [comment]
First thanks to your work!

Indeed, SVG Elements kind of brake the rule of being CSS only. But as long it is an option I don't see any problems. I will need to take a closer look but I guess I will it, since in the end the goal of this lib is to help people create their dream interface, and for many things you will need either really advanced CSS or inkscape. But I wonder how we make eventhooks, so like upper left is clicked...

**Comment by joernweissenborn** [comment]
What does @tenleftfingers thinks?

**Comment by jrwarwick** [comment]
Each polygin or enclosed path can have id and class, I just didn't get
those parts classed. I will address that with another commit if you and
tenleftfingers approve the addition.

  --Justin

**Comment by joernweissenborn** [comment]
Please add demo on how to make make the SVG interactive to the index. Then
we can see how it all works. For me it is important that things work well
outside the demo case. So somebody who can use Inkscape and write CSS
should have an easy way to connect certain things within a SVG to the
framework (Angular or whatever). I myself all the time had the plan to
bring in some interactive SVG, but it don't know how far you can go with
just CSS.

Am So., 17. Nov. 2019 um 00:57 Uhr schrieb Justin Warwick <
notifications@github.com>:

**Comment by tenleftfingers** [comment]
Nice work @jrwarwick! I've been considering how to achieve more complex elements such as this and SVG did cross my mind. I think if we can see it working it would help. Also if it is possible, as @joernweissenborn says, to keep it optional then it's a good addition to fill some gaps.

Incidentally, I've finished screenshotting LCARS from Season 1 of TNG and this element is very close to the season 1 original (see attached screenshots).
[lcars-xy-control.zip](https://github.com/joernweissenborn/lcars/files/3855169/lcars-xy-control.zip)

**Comment by jrwarwick** [comment]
- A few refinements committed including making the diagonal buttons addressable and automatically active and expounding on usage on the index doc.
- Issue #26 (support for complex geometry elements) filed to correspond to this PR.
- Demo preview of branch published temporarily here: [https://jrwarwick.github.io/lcars_demo/](https://jrwarwick.github.io/lcars_demo/)

@tenleftfingers thanks for those references, very useful. I had been using this page for reference:
http://www.startrekpropauthority.com/2010/10/star-trek-experience-tng-captains-chair.html
as the images are pretty high resolution, and many of them have a straight-on shot which is harder to find in cinematic/perspective shots.
Especially I used this image: 
http://4.bp.blogspot.com/_XNPD380IpBQ/TKqtIsBF7vI/AAAAAAAALw8/G6SRxJgggms/s1600/P317_10.jpg

But alas, I see now that these particular items were from the Star Trek Experience, not from on-screen! So I will work on color corrections and the variations on black markings on the main shapes later, if the addition is accepted.

**Comment by joernweissenborn** [comment]
@jrwarwick please look at the `AUTHORS` file I just created. You can find my mail address there. Please write me so you can join our slack to discuss further.

**Comment by joernweissenborn** [comment]
Regarding the colors: you should use those I provide, it is basically the _complete_ scheme. I dug it up in guide, today it can still be found as picture by just googling `lcars colors codes`

**Comment by jrwarwick** [comment]
@joernweissenborn Using the colors that you provide is certainly my intention. Did you find a color in the SVG elements that deviates? I recall copying and pasting the RGB values (from a chrome DOM inspection). This is what it looks like on my Chrome-on-Windows screen:
image

**Comment by jrwarwick** [comment]
Just noticed a little filename bug change is in this PR, even though it probably should have had its own. 
So, this PR will resolve #30

**Pull request merged**
